name: flutter-tests

on: [push]

jobs:
  analysis:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Flutter
        uses: ./.github/actions/initialize-flutter
      - name: Check Code Format
        run: dart format . --set-exit-if-changed
      - name: Analyze code
        run: dart analyze .
  widget-tests:
    name: widget-tests
    runs-on: ubuntu-latest
    needs: analysis
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Flutter
        uses: ./.github/actions/initialize-flutter
      - name: Generate code
        run: dart run build_runner build
      - name: Run tests
        run: flutter test
